// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:43b74329-ded5-45eb-baef-e3e657c55571',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'chatapp-hosting-mobilehub-1762768659',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2ezmfg01h1sc7.cloudfront.net',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': '2852d28940d3456180abc490253d42b5',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '82e3dfa1-8b95-45f5-b73a-74637b02c9c2',
    'aws_project_name': 'chatApp',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'chatapp-mobilehub-1762768659',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_Tzcu4gwzZ',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '2gr46dsqefb1a0v3vqq0ah0kjq',
}

export default awsmobile;
